### ISSUE TITLE
Agregar residuales en el ajuste lineal

### ISSUE THREAD

**Issue by alfredoq** [alfredoq/Seminarios-FQI-FCQ-UNC#4]
Cuando se hacen las regresiones lineales para determinar el órden de reacción, también podríamos calcular los residuales y la suma de los cuadrados (SSR) de los residuales como criterio de calidad de ajuste lineal simado del R2. 

Aca hay un ejemplo:
https://www.geeksforgeeks.org/how-to-calculate-residual-sum-of-squares-in-python/

prodemos graficar los residuales para evaluar la distribución.

**Comment by juampicerutti** [comment]
Ya lo hice, pero hay inconsistencia entre el resultado de r2 y del SSR.

**Comment by alfredoq** [comment]
Solved
